version: '3.8'

volumes:
  strategies_code_vol:

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./quant_trade.db
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - strategies_code_vol:/strategies_code

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./quant_trade.db
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - strategies_code_vol:/strategies_code

