version: '3.8'

volumes:
  strategies_code_vol:
  quant_trade_db_vol:

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./data/quant_trade.db
      - TQ_USER=${TQ_USER}
      - TQ_PASSWORD=${TQ_PASSWORD}
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - strategies_code_vol:/strategies_code
      - quant_trade_db_vol:/app/data

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app/app
    command: celery -A celery_app worker --loglevel=info --uid=nobody
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./data/quant_trade.db
      - TQ_USER=${TQ_USER}
      - TQ_PASSWORD=${TQ_PASSWORD}
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - strategies_code_vol:/strategies_code
      - quant_trade_db_vol:/app/data

